import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('adminLanguage');
    return saved || 'mr'; // Default to Marathi
  });

  useEffect(() => {
    localStorage.setItem('adminLanguage', language);
    // Update document direction for RTL/LTR if needed
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'mr' ? 'en' : 'mr');
  };

  const translations = {
    mr: {
      dashboard: 'डॅशबोर्ड',
      articles: 'लेख',
      createArticle: 'नवीन लेख तयार करा',
      welcome: 'स्वागत',
      logout: 'बाहेर पडा',
      notifications: 'सूचना',
      theme: 'थीम',
      category: 'वर्ग',
      city: 'शहर',
      placement: 'स्थान',
      title: 'शीर्षक',
      content: 'सामग्री',
      thumbnail: 'थंबनेल',
      save: 'सेव्ह करा',
      cancel: 'रद्द करा',
      edit: 'संपादित करा',
      delete: 'हटवा',
      search: 'शोधा',
      filter: 'फिल्टर',
      date: 'तारीख',
      actions: 'क्रिया',
      loading: 'लोडिंग...',
      noDataFound: 'कोणतेही डेटा सापडले नाही',
      previous: 'आधीचे',
      next: 'पुढील',
      page: 'पृष्ठ',
      of: 'पैकी',
      showing: 'दाखवत आहे',
      to: 'पर्यंत',
      all: 'सर्व',
      allCategories: 'सर्व वर्ग',
      selectCategory: 'वर्ग निवडा',
      selectCity: 'शहर निवडा',
      enterTitle: 'लेखाचे शीर्षक प्रविष्ट करा',
      enterContent: 'लेखाची सामग्री प्रविष्ट करा',
      supportedFormats: 'समर्थित: JPG, PNG, GIF, WebP',
      videoArticle: 'व्हिडिओ लेख',
      yes: 'होय',
      no: 'नाही',
      articleType: 'लेख प्रकार',
      article: 'लेख',
      video: 'व्हिडिओ',
      videoNews: 'व्हिडिओ बातमी',
      featuredArticle: 'फीचर्ड लेख',
      featured: 'फीचर्ड',
      priority: 'प्राधान्य',
      videoUrl: 'व्हिडिओ URL',
      enterVideoUrl: 'व्हिडिओ URL प्रविष्ट करा',
      videoUrlRequired: 'व्हिडिओ प्रकारासाठी व्हिडिओ URL आवश्यक आहे',
      allTypes: 'सर्व प्रकार',
      featuredOnly: 'फक्त फीचर्ड',
      nonFeatured: 'फीचर्ड नाही',
      priorityHint: 'कमी संख्या = उच्च प्राधान्य',
      featuredExplanation: 'होमपेजवर हिरो सेक्शनमध्ये दाखवण्यासाठी लेख निवडा',
      priorityExplanation: 'फीचर्ड लेखांच्या क्रमवारीसाठी वापरले जाते (2 = सर्वात वर)',
      priorityNormal: 'सामान्य',
      priorityImportant: 'महत्वाचे',
      priorityVeryImportant: 'अत्यंत महत्वाचे',
      admin: 'प्रशासक',
      security: 'सुरक्षा',
      changePassword: 'पासवर्ड बदला',
      currentPassword: 'वर्तमान पासवर्ड',
      newPassword: 'नवीन पासवर्ड',
      confirmNewPassword: 'नवीन पासवर्ड पुष्टी करा',
      updatePassword: 'पासवर्ड अपडेट करा',
      updating: 'अपडेट होत आहे...',
      accountInfo: 'खाते माहिती',
      email: 'ईमेल',
      created: 'तयार केले',
      quickActions: 'त्वरित क्रिया',
      manageArticles: 'लेख व्यवस्थापित करा',
      addNewArticle: 'नवीन लेख जोडा',
      viewEditDeleteArticles: 'लेख पाहा, संपादित करा, हटवा',
      firebaseNotifications: 'फायरबेस पुश सूचना',
      comingSoon: 'लवकर येत आहे',
      switchToLight: 'लाईट मोडवर जा',
      switchToDark: 'डार्क मोडवर जा',
      language: 'भाषा',
      marathi: 'मराठी',
      english: 'इंग्रजी',
      saving: 'सेव्ह होत आहे...',
      addNewCategory: 'नवीन वर्ग जोडा',
      addNewCity: 'नवीन शहर जोडा',
      addCategory: 'वर्ग जोडा',
      addCity: 'शहर जोडा',
      enterCategoryName: 'वर्गाचे नाव प्रविष्ट करा',
      enterCityName: 'शहराचे नाव प्रविष्ट करा',
      advertisements: 'जाहिराती',
      createAd: 'जाहिरात तयार करा',
      addNewAd: 'नवीन जाहिरात जोडा',
      editAdvertisement: 'जाहिरात संपादित करा',
      createAdvertisement: 'जाहिरात तयार करा',
      advertisementNotFound: 'जाहिरात सापडली नाही',
      failedToFetchAdvertisements: 'जाहिराती मिळवण्यात अयशस्वी',
      advertisementDeleted: 'जाहिरात हटवली',
      advertisementUpdated: 'जाहिरात अद्यतनित',
      advertisementCreated: 'जाहिरात तयार केली',
      advertisementStatus: 'जाहिरात स्थिती',
      topBanner: 'टॉप बॅनर',
      sidebar: 'साइडबार',
      allPlacements: 'सर्व प्लेसमेंट',
      mediaImageVideo: 'माध्यम (चित्र किंवा व्हिडिओ)',
      enterAdvertisementTitle: 'जाहिरातीचे शीर्षक प्रविष्ट करा',
      redirectUrl: 'रीडायरेक्ट URL',
      startDate: 'प्रारंभ तारीख',
      endDate: 'समाप्ती तारीख',
      isActive: 'सक्रिय आहे',
      advertisementDetails: 'जाहिरातीची तपशील',
      media: 'माध्यम',
      type: 'प्रकार',
      duration: 'कालावधी',
      status: 'स्थिती',
      actions: 'क्रिया',
      active: 'सक्रिय',
      inactive: 'निष्क्रिय',
      filter: 'फिल्टर',
      noAdvertisementsFound: 'कोणतीही जाहिरात सापडली नाही',
      edit: 'संपादित करा',
      delete: 'हटवा',
      showing: 'दाखवत आहे',
      to: 'पर्यंत',
      of: 'पैकी',
      ads: 'जाहिराती',
      previous: 'आधीचे',
      next: 'पुढील',
      page: 'पृष्ठ',
      supportedFormats: 'समर्थित: JPEG, PNG, GIF, WebP व MP4, WebM, MOV - अधिकतम 50MB',
      redirectUrlOptional: 'रीडायरेक्ट URL (वैकल्पिक)',
      startDateRequired: 'प्रारंभ तारीख *',
      endDateRequired: 'समाप्ती तारीख *',
      cancel: 'रद्द करा',
      updateAdvertisement: 'जाहिरात अद्यतनित करा',
      saving: 'सेव्ह होत आहे'
    },
    en: {
      dashboard: 'Dashboard',
      articles: 'Articles',
      createArticle: 'Create Article',
      welcome: 'Welcome',
      logout: 'Logout',
      notifications: 'Notifications',
      theme: 'Theme',
      category: 'Category',
      city: 'City',
      placement: 'Placement',
      title: 'Title',
      content: 'Content',
      thumbnail: 'Thumbnail',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      search: 'Search',
      filter: 'Filter',
      date: 'Date',
      actions: 'Actions',
      loading: 'Loading...',
      noDataFound: 'No data found',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
      showing: 'Showing',
      to: 'to',
      all: 'All',
      allCategories: 'All Categories',
      selectCategory: 'Select Category',
      selectCity: 'Select City',
      enterTitle: 'Enter article title',
      enterContent: 'Enter article content',
      supportedFormats: 'Supported: JPG, PNG, GIF, WebP',
      videoArticle: 'Video Article',
      yes: 'Yes',
      no: 'No',
      articleType: 'Article Type',
      article: 'Article',
      video: 'Video',
      videoNews: 'Video News',
      featuredArticle: 'Featured Article',
      featured: 'Featured',
      priority: 'Priority',
      videoUrl: 'Video URL',
      enterVideoUrl: 'Enter video URL',
      videoUrlRequired: 'Video URL is required for video type',
      allTypes: 'All Types',
      featuredOnly: 'Featured Only',
      nonFeatured: 'Non-Featured',
      priorityHint: 'Lower number = Higher priority',
      featuredExplanation: 'Select article to display in homepage hero section',
      priorityExplanation: 'Used for ordering featured articles (2 = highest)',
      priorityNormal: 'Normal',
      priorityImportant: 'Important',
      priorityVeryImportant: 'Very Important',
      admin: 'Admin',
      security: 'Security',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      updating: 'Updating...',
      accountInfo: 'Account Information',
      email: 'Email',
      created: 'Created',
      quickActions: 'Quick Actions',
      manageArticles: 'Manage Articles',
      addNewArticle: 'Add New Article',
      viewEditDeleteArticles: 'View, edit, delete articles',
      firebaseNotifications: 'Firebase Push Notifications',
      comingSoon: 'Coming Soon',
      switchToLight: 'Switch to Light Mode',
      switchToDark: 'Switch to Dark Mode',
      language: 'Language',
      marathi: 'Marathi',
      english: 'English',
      saving: 'Saving...',
      addNewCategory: 'Add New Category',
      addNewCity: 'Add New City',
      addCategory: 'Add Category',
      addCity: 'Add City',
      enterCategoryName: 'Enter category name',
      enterCityName: 'Enter city name',
      advertisements: 'Advertisements',
      createAd: 'Create Ad',
      addNewAd: 'Add New Ad',
      editAdvertisement: 'Edit Advertisement',
      createAdvertisement: 'Create Advertisement',
      advertisementNotFound: 'Advertisement not found',
      failedToFetchAdvertisements: 'Failed to fetch advertisements',
      advertisementDeleted: 'Advertisement deleted',
      advertisementUpdated: 'Advertisement updated',
      advertisementCreated: 'Advertisement created',
      advertisementStatus: 'Advertisement Status',
      topBanner: 'Top Banner',
      sidebar: 'Sidebar',
      allPlacements: 'All Placements',
      mediaImageVideo: 'Media (Image or Video)',
      enterAdvertisementTitle: 'Enter advertisement title',
      redirectUrl: 'Redirect URL',
      startDate: 'Start Date',
      endDate: 'End Date',
      isActive: 'Is Active',
      advertisementDetails: 'Advertisement Details',
      media: 'Media',
      type: 'Type',
      duration: 'Duration',
      status: 'Status',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      filter: 'Filter',
      noAdvertisementsFound: 'No advertisements found',
      edit: 'Edit',
      delete: 'Delete',
      showing: 'Showing',
      to: 'to',
      of: 'of',
      ads: 'ads',
      previous: 'Previous',
      next: 'Next',
      page: 'Page',
      supportedFormats: 'Supported formats: JPEG, PNG, GIF, WebP and MP4, WebM, MOV - Max 50MB',
      redirectUrlOptional: 'Redirect URL (Optional)',
      startDateRequired: 'Start Date *',
      endDateRequired: 'End Date *',
      cancel: 'Cancel',
      updateAdvertisement: 'Update Advertisement',
      saving: 'Saving...'
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isMarathi: language === 'mr' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
